# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dps-proxy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e2b36385c9014b85bc3d399195fc4ad9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3bd3d446f2dc40eaab8e93f645e94d55 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_e2b36385c9014b85bc3d399195fc4ad9 }}/ridomin/dps-proxy:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dps-proxy'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a3336e31fedc48c1b3fefb62060e2f7f }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_e2b36385c9014b85bc3d399195fc4ad9 }}/ridomin/dps-proxy:${{ github.sha }}'